server:
  port: ${PORT:8083}

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
  client:
    serviceUrl:
      defaultZone: ${DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: true
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
        - id: ordersModule
          uri: lb://MICROSERVICEONE
          predicates:
            - Path=/orders/**
        - id: productsModule
          uri: lb://MICROSERVICETWO
          predicates:
            - Path=/products/**