server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    use-read-only-response-cache: false
    response-cache-auto-expiration-in-seconds: 10
    response-cache-update-interval-ms: 5000
  instance:
    hostname: eurekaserver-1

spring:
  application:
    name: EurekaServer